# Generated by Django 6.0.4 on 2026-04-14 13:55

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='исходное/оригинальное имя файла')),
                ('stored_name', models.CharField(max_length=255, unique=True, verbose_name='уникальное имя файла на диске')),
                ('file', models.FileField(upload_to=apps.files.models.user_file_upload_to, verbose_name='файл')),
                ('size', models.PositiveBigIntegerField(verbose_name='размер файла в байтах')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к файлу')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки файла')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='дата последнего скачивания файла')),
                ('public_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='уникальный токен для публичного доступа к файлу')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='владелец файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['owner'], name='files_store_owner_i_178595_idx'), models.Index(fields=['public_token'], name='files_store_public__0ad57a_idx')],
            },
        ),
    ]
